
package cz.zcu.stag_ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * Eclipse Metro/4.0.2 (RELEASE-4.0.2-ffda8c0; 2023-01-31T10:50:38+0000) XMLWS-Impl/4.0.1 XMLWS-API/4.0.0 XMLB-Impl/4.0.2 XMLB-API/4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProgramyService", targetNamespace = "http://stag-ws.zcu.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProgramyService {


    /**
     * 
     * @param lang
     * @param sespIdno
     * @return
     *     returns cz.zcu.stag_ws.BlokInfoListType
     */
    @WebMethod
    @WebResult(name = "blokInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getBlokySegmentu", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokySegmentu")
    @ResponseWrapper(localName = "getBlokySegmentuResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokySegmentuResponse")
    public BlokInfoListType getBlokySegmentu(
        @WebParam(name = "sespIdno", targetNamespace = "")
        long sespIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param oborIdno
     * @return
     *     returns cz.zcu.stag_ws.OborInfoType
     */
    @WebMethod
    @WebResult(name = "oborInfo", targetNamespace = "")
    @RequestWrapper(localName = "getOborInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOborInfo")
    @ResponseWrapper(localName = "getOborInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOborInfoResponse")
    public OborInfoType getOborInfo(
        @WebParam(name = "oborIdno", targetNamespace = "")
        long oborIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param sespIdno
     * @return
     *     returns cz.zcu.stag_ws.SegmentInfoType
     */
    @WebMethod
    @WebResult(name = "segmentInfo", targetNamespace = "")
    @RequestWrapper(localName = "getSegmentInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetSegmentInfo")
    @ResponseWrapper(localName = "getSegmentInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetSegmentInfoResponse")
    public SegmentInfoType getSegmentInfo(
        @WebParam(name = "sespIdno", targetNamespace = "")
        long sespIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param stplIdno
     * @return
     *     returns cz.zcu.stag_ws.BlokInfoListType
     */
    @WebMethod
    @WebResult(name = "blokInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getBlokyPlanu", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokyPlanu")
    @ResponseWrapper(localName = "getBlokyPlanuResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokyPlanuResponse")
    public BlokInfoListType getBlokyPlanu(
        @WebParam(name = "stplIdno", targetNamespace = "")
        long stplIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param rok
     * @param stprIdno
     * @return
     *     returns cz.zcu.stag_ws.OborInfoListType
     */
    @WebMethod
    @WebResult(name = "oborInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getOboryStudijnihoProgramu", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOboryStudijnihoProgramu")
    @ResponseWrapper(localName = "getOboryStudijnihoProgramuResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOboryStudijnihoProgramuResponse")
    public OborInfoListType getOboryStudijnihoProgramu(
        @WebParam(name = "stprIdno", targetNamespace = "")
        long stprIdno,
        @WebParam(name = "rok", targetNamespace = "")
        String rok,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param fakulta
     * @param forma
     * @param jazyk
     * @param kod
     * @param lang
     * @param pouzePlatne
     * @param profil
     * @param rok
     * @param typ
     * @return
     *     returns cz.zcu.stag_ws.ProgramInfoListType
     */
    @WebMethod
    @WebResult(name = "programInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getStudijniProgramy", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetStudijniProgramy")
    @ResponseWrapper(localName = "getStudijniProgramyResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetStudijniProgramyResponse")
    public ProgramInfoListType getStudijniProgramy(
        @WebParam(name = "fakulta", targetNamespace = "")
        String fakulta,
        @WebParam(name = "rok", targetNamespace = "")
        String rok,
        @WebParam(name = "kod", targetNamespace = "")
        String kod,
        @WebParam(name = "forma", targetNamespace = "")
        String forma,
        @WebParam(name = "typ", targetNamespace = "")
        String typ,
        @WebParam(name = "jazyk", targetNamespace = "")
        String jazyk,
        @WebParam(name = "profil", targetNamespace = "")
        String profil,
        @WebParam(name = "pouzePlatne", targetNamespace = "")
        Boolean pouzePlatne,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param oborIdno
     * @param rok
     * @return
     *     returns cz.zcu.stag_ws.PlanInfoListType
     */
    @WebMethod
    @WebResult(name = "planInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getPlanyOboru", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanyOboru")
    @ResponseWrapper(localName = "getPlanyOboruResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanyOboruResponse")
    public PlanInfoListType getPlanyOboru(
        @WebParam(name = "oborIdno", targetNamespace = "")
        long oborIdno,
        @WebParam(name = "rok", targetNamespace = "")
        String rok,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param fakulta
     * @param forma
     * @param jazyk
     * @param oborIdno
     * @param pouzePlatne
     * @param rok
     * @param typ
     * @return
     *     returns cz.zcu.stag_ws.OborQRAMInfoListType
     */
    @WebMethod
    @WebResult(name = "oborQRAMInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getOboryQRAMInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOboryQRAMInfo")
    @ResponseWrapper(localName = "getOboryQRAMInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOboryQRAMInfoResponse")
    public OborQRAMInfoListType getOboryQRAMInfo(
        @WebParam(name = "oborIdno", targetNamespace = "")
        Long oborIdno,
        @WebParam(name = "fakulta", targetNamespace = "")
        String fakulta,
        @WebParam(name = "rok", targetNamespace = "")
        String rok,
        @WebParam(name = "forma", targetNamespace = "")
        String forma,
        @WebParam(name = "typ", targetNamespace = "")
        String typ,
        @WebParam(name = "jazyk", targetNamespace = "")
        String jazyk,
        @WebParam(name = "pouzePlatne", targetNamespace = "")
        Boolean pouzePlatne);

    /**
     * 
     * @param lang
     * @param stplIdno
     * @return
     *     returns cz.zcu.stag_ws.PlanInfoType
     */
    @WebMethod
    @WebResult(name = "planInfo", targetNamespace = "")
    @RequestWrapper(localName = "getPlanInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanInfo")
    @ResponseWrapper(localName = "getPlanInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanInfoResponse")
    public PlanInfoType getPlanInfo(
        @WebParam(name = "stplIdno", targetNamespace = "")
        long stplIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param stprIdno
     * @return
     *     returns cz.zcu.stag_ws.ProgramOblVzdelListType
     */
    @WebMethod
    @WebResult(name = "programOblVzdelList", targetNamespace = "")
    @RequestWrapper(localName = "getOblastiVzdelavaniProgramu", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOblastiVzdelavaniProgramu")
    @ResponseWrapper(localName = "getOblastiVzdelavaniProgramuResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetOblastiVzdelavaniProgramuResponse")
    public ProgramOblVzdelListType getOblastiVzdelavaniProgramu(
        @WebParam(name = "stprIdno", targetNamespace = "")
        long stprIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param osCislo
     * @param rok
     * @return
     *     returns cz.zcu.stag_ws.PlanInfoListType
     */
    @WebMethod
    @WebResult(name = "planyInfo", targetNamespace = "")
    @RequestWrapper(localName = "getPlanyStudenta", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanyStudenta")
    @ResponseWrapper(localName = "getPlanyStudentaResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetPlanyStudentaResponse")
    public PlanInfoListType getPlanyStudenta(
        @WebParam(name = "osCislo", targetNamespace = "")
        String osCislo,
        @WebParam(name = "rok", targetNamespace = "")
        String rok,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param stprIdno
     * @return
     *     returns cz.zcu.stag_ws.ProgramInfoType
     */
    @WebMethod
    @WebResult(name = "programInfo", targetNamespace = "")
    @RequestWrapper(localName = "getStudijniProgramInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetStudijniProgramInfo")
    @ResponseWrapper(localName = "getStudijniProgramInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetStudijniProgramInfoResponse")
    public ProgramInfoType getStudijniProgramInfo(
        @WebParam(name = "stprIdno", targetNamespace = "")
        long stprIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param lang
     * @param stplIdno
     * @return
     *     returns cz.zcu.stag_ws.SegmentInfoListType
     */
    @WebMethod
    @WebResult(name = "segmentInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getSegmentyPlanu", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetSegmentyPlanu")
    @ResponseWrapper(localName = "getSegmentyPlanuResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetSegmentyPlanuResponse")
    public SegmentInfoListType getSegmentyPlanu(
        @WebParam(name = "stplIdno", targetNamespace = "")
        long stplIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

    /**
     * 
     * @param blokIdno
     * @param lang
     * @return
     *     returns cz.zcu.stag_ws.BlokInfoType
     */
    @WebMethod
    @WebResult(name = "blokInfo", targetNamespace = "")
    @RequestWrapper(localName = "getBlokInfo", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokInfo")
    @ResponseWrapper(localName = "getBlokInfoResponse", targetNamespace = "http://stag-ws.zcu.cz/", className = "cz.zcu.stag_ws.GetBlokInfoResponse")
    public BlokInfoType getBlokInfo(
        @WebParam(name = "blokIdno", targetNamespace = "")
        long blokIdno,
        @WebParam(name = "lang", targetNamespace = "")
        String lang);

}
