
package cz.upol.pja.lecture06;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * Eclipse Metro/4.0.2 (RELEASE-4.0.2-ffda8c0; 2023-01-31T10:50:38+0000) XMLWS-Impl/4.0.1 XMLWS-API/4.0.0 XMLB-Impl/4.0.2 XMLB-API/4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServiceBmi", targetNamespace = "http://lecture06.pja.upol.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceBmi {


    /**
     * 
     * @param weight
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateBmi", targetNamespace = "http://lecture06.pja.upol.cz/", className = "cz.upol.pja.lecture06.CalculateBmi")
    @ResponseWrapper(localName = "calculateBmiResponse", targetNamespace = "http://lecture06.pja.upol.cz/", className = "cz.upol.pja.lecture06.CalculateBmiResponse")
    @Action(input = "http://lecture06.pja.upol.cz/ServiceBmi/calculateBmiRequest", output = "http://lecture06.pja.upol.cz/ServiceBmi/calculateBmiResponse")
    public String calculateBmi(
        @WebParam(name = "weight", targetNamespace = "")
        String weight,
        @WebParam(name = "height", targetNamespace = "")
        String height);

}
